[package]
name = "libjvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libjava = { path = "../libjava" }
libjit = { path = "../libjit" }
libvfs = { path = "../libvfs" }
